# Generated by Django 3.0.4 on 2020-05-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('users', '0002_auto_20200502_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_plate',
            field=models.ManyToManyField(to='forum.Plate'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following_post',
            field=models.ManyToManyField(to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following_stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.FollowingStocks'),
        ),
    ]
