# Generated by Django 3.0.4 on 2020-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200517_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '女'), (1, '男'), (2, '无')], null=True),
        ),
    ]
