# Generated by Django 3.0.4 on 2020-05-26 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200517_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='capital',
            field=models.FloatField(default=200000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cash',
            field=models.FloatField(default=200000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=20),
        ),
    ]
