# Generated by Django 3.0.4 on 2020-05-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_auto_20200526_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=128)),
                ('code', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('whole_balance', models.FloatField(default=0)),
                ('available_balance', models.FloatField(default=0)),
                ('blocked_balance', models.FloatField(default=0)),
                ('thisday_blocked_balance', models.FloatField(default=0)),
                ('cost', models.FloatField(default=1)),
                ('price', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('profit_proportion', models.FloatField(default=0)),
                ('market_value', models.FloatField(default=0)),
                ('whole_buy', models.FloatField(default=0)),
                ('whole_sell', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=128)),
                ('date', models.CharField(default='', max_length=128)),
                ('time1', models.CharField(default='', max_length=128)),
                ('code', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('operation', models.CharField(default='', max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('poundage', models.FloatField(default=0)),
                ('stamp_tax', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, max_length=128)),
                ('date', models.CharField(default='', max_length=128)),
                ('time1', models.CharField(default='', max_length=128)),
                ('code', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('operation', models.CharField(default='', max_length=128)),
                ('note', models.CharField(default='', max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
    ]
